coverage:
  status:
    project:
      default:
        target: 65%
        threshold: 1%
    patch:
      default:
        target: 65%
        threshold: 1%

ignore:
  - "internal/mock"
  - "**/*_test.go"
