coverage:
  status:
    project:
      default:
        target: 55%
        threshold: 1%
    patch:
      default:
        target: 55%
        threshold: 1%

ignore:
  - "internal/mock"
  - "**/*_test.go"
  - "cmd/staticlint"
  - "proto"
