// Code generated by MockGen. DO NOT EDIT.
// Source: internal/models/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/models/repository.go -destination=internal/models/mock_repository.go -package=models
//

// Package models is a generated GoMock package.
package mock

import (
	"github.com/Gerfey/shortener/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockRepository) All() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// All indicates an expected call of All.
func (mr *MockRepositoryMockRecorder) All() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockRepository)(nil).All))
}

// Find mocks base method.
func (m *MockRepository) Find(key string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRepositoryMockRecorder) Find(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRepository)(nil).Find), key)
}

// Save mocks base method.
func (m *MockRepository) Save(key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryMockRecorder) Save(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).Save), key, value)
}

// MockStorageStrategy is a mock of StorageStrategy interface.
type MockStorageStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockStorageStrategyMockRecorder
	isgomock struct{}
}

// MockStorageStrategyMockRecorder is the mock recorder for MockStorageStrategy.
type MockStorageStrategyMockRecorder struct {
	mock *MockStorageStrategy
}

// NewMockStorageStrategy creates a new mock instance.
func NewMockStorageStrategy(ctrl *gomock.Controller) *MockStorageStrategy {
	mock := &MockStorageStrategy{ctrl: ctrl}
	mock.recorder = &MockStorageStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageStrategy) EXPECT() *MockStorageStrategyMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStorageStrategy) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStorageStrategyMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStorageStrategy)(nil).Close))
}

// Initialize mocks base method.
func (m *MockStorageStrategy) Initialize() (models.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize")
	ret0, _ := ret[0].(models.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Initialize indicates an expected call of Initialize.
func (mr *MockStorageStrategyMockRecorder) Initialize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockStorageStrategy)(nil).Initialize))
}
